export const GET_BASIS_INFO_SUCCESS = 'GET_BASIS_INFO_SUCCESS'
export const GET_BASIS_INFO_FAIL = 'GET_BASIS_INFO_FAIL'
export const CHANGE_INFO_SUCCESS = 'CHANGE_INFO_SUCCESS'
export const CHANGE_INFO_FAIL = 'CHANGE_INFO_FAIL'
