// 获取电站统计信息
export const GET_PLANT_INFO_SUCCESS = 'GET_PLANT_INFO_SUCCESS'
export const GET_PLANT_INFO_FAIL = 'GET_PLANT_INFO_FAIL'

// 获取实时功率
export const GET_PLANT_POWER_DATA_SUCCESS = 'GET_PLANT_POWER_DATA_SUCCESS'
export const GET_PLANT_POWER_DATA_FAIL = 'GET_PLANT_POWER_DATA_FAIL'

// 获取日发电量
export const GET_PLANT_DAY_ENERGY_SUCCESS = 'GET_PLANT_DAY_ENERGY_SUCCESS'
export const GET_PLANT_DAY_ENERGY_FAIL = 'GET_PLANT_DAY_ENERGY_FAIL'

// 获取月发电量
export const GET_PLANT_MONTH_ENERGY_SUCCESS = 'GET_PLANT_MONTH_ENERGY_SUCCESS'
export const GET_PLANT_MONTH_ENERGY_FAIL = 'GET_PLANT_MONTH_ENERGY_FAIL'

// 获取月发电量
export const GET_PLANT_YEAR_ENERGY_SUCCESS = 'GET_PLANT_YEAR_ENERGY_SUCCESS'
export const GET_PLANT_YEAR_ENERGY_FAIL = 'GET_PLANT_YEAR_ENERGY_FAIL'
