// 获取用户所有电站概况的基本信息
export const GET_USER_STAT_SUCCESS = 'GET_USER_STAT_SUCCESS'
export const GET_USER_STAT_FAIL = 'GET_USER_STAT_FAIL'

// 获取实时功率
export const GET_USER_POWER_DATA_SUCCESS = 'GET_USER_POWER_DATA_SUCCESS'
export const GET_USER_POWER_DATA_FAIL = 'GET_USER_POWER_DATA_FAIL'

// 获取日发电量
export const GET_USER_DAY_ENERGY_SUCCESS = 'GET_USER_DAY_ENERGY_SUCCESS'
export const GET_USER_DAY_ENERGY_FAIL = 'GET_USER_DAY_ENERGY_FAIL'

// 获取月发电量
export const GET_USER_MONTH_ENERGY_SUCCESS = 'GET_USER_MONTH_ENERGY_SUCCESS'
export const GET_USER_MONTH_ENERGY_FAIL = 'GET_USER_MONTH_ENERGY_FAIL'

// 获取月发电量
export const GET_USER_YEAR_ENERGY_SUCCESS = 'GET_USER_YEAR_ENERGY_SUCCESS'
export const GET_USER_YEAR_ENERGY_FAIL = 'GET_USER_YEAR_ENERGY_FAIL'
